server: 
   port: 9082
spring: 
   application: 
      name: pack-saga-demo
   http: 
      encoding: 
         charse: UTF-8
   messages: 
      encoding: UTF-8
      
   datasource: 
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      platform: mysql
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: 123456
      ##以下是DruidDataSource参数配置
      initialSize: 5
      minIdle: 2
      maxActive: 10
      maxWait: 60000   # 配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false         
      filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,防止sql注入
      logSlowSql: true
 
   cloud: 
      nacos:
         discovery:
            enabled: false
            server-addr: 127.0.0.1:8848   
      zookeeper: 
         enabled: false
         connectString: 127.0.0.1:2181
      
 
mybatis: 
   type-aliases-package: com.dtx.servicecomb.saga.entity
   mapperLocations: classpath*:mapper/*.xml
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页     
pagehelper: 
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   
   
alpha:
   cluster:
      address: 127.0.0.1:8080
      #register:
      #   type: nacos
      
         